/**
 * TestHalfElf.java Copyright (c) 2017, Alan Cline. All Rights Reserved.
 * 
 * Permission to make digital or hard copies of all or parts of this work for commercial use is
 * prohibited. To republish, to post on servers, to reuse, or to redistribute to lists,
 * requires prior specific permission and/or a fee. Request permission to use from
 * acline@wowway.com.
 */

package chronos.test.pdc.race;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import chronos.pdc.Chronos;
import chronos.pdc.character.Gender;
import chronos.pdc.character.TraitList;
import chronos.pdc.character.TraitList.PrimeTraits;
import chronos.pdc.race.HalfElf;
import mylib.MsgCtrl;
import mylib.pdc.Utilities;

/**
 * @author --generated by QA Tool--
 * @version September 16, 2017 // original <br>
 *          May 11, 2018 // removed detailed stat tests <br>
 *          May 24, 2018 // removed dup tests and simplied Override methods <br>
 *          May 26, 2018 // Verified gender adj and standardized <br>
 */
public class TestHalfElf
{
  // Generate a bunch of values in a loop for stat calculation
  private int NBR_LOOPS = 1000;

  private HalfElf _him;
  private HalfElf _her;
  /** Female characters also need gender adjustments: STR-1, CON+1, CHR+1 */
  static private Gender _gender;

  @BeforeAll
  public static void setUpBeforeClass() throws Exception
  {
    _gender = new Gender("Female");
    assertNotNull(_gender);
  }

  @AfterAll
  public static void tearDownAfterClass() throws Exception
  {
    _gender = null;
  }

  /**
   * @throws java.lang.Exception -- general catch-all for exceptions not caught by the tests
   */
  @BeforeEach
  public void setUp() throws Exception
  {
    _him = new HalfElf(new Gender("male"), "black");
    assertNotNull(_him);

    _her = new HalfElf(new Gender("female"), "brown");
    assertNotNull(_her);
  }

  /**
   * @throws java.lang.Exception -- general catch-all for exceptions not caught by the tests
   */
  @AfterEach
  public void tearDown() throws Exception
  {
    MsgCtrl.auditMsgsOn(false);
    MsgCtrl.errorMsgsOn(false);

    _her = null;
    _him = null;
  }


  // ===============================================================================
  // BEGIN TESTING
  // ===============================================================================

  /**
   * @Normal.Test void adjustTraitsForRace(TraitList) -- Half-Elves have no modifications
   */
  @Test
  public void testAdjustTraitsForRace()
  {
    MsgCtrl.auditMsgsOn(false);
    MsgCtrl.errorMsgsOn(false);
    MsgCtrl.where(this);

    // Save the original TraitList to an array for later comparison
    // STR, INT, WIS, CON, DEX, CHR
    TraitList traits = new TraitList();
    int[] original = traits.toArray();
    MsgCtrl.msgln("\t Raw traits:\t\t\t" + traits.toString());

    // No adj for Half-Elves
    _him.adjustTraitsForRace(traits);
    MsgCtrl.msgln("\t No Race adj:\t\t\t " + traits.toString());
    assertEquals(original[0], traits.getTrait(PrimeTraits.STR));
    assertEquals(original[1], traits.getTrait(PrimeTraits.INT));
    assertEquals(original[2], traits.getTrait(PrimeTraits.WIS));
    assertEquals(original[3], traits.getTrait(PrimeTraits.CON));
    assertEquals(original[4], traits.getTrait(PrimeTraits.DEX));
    assertEquals(original[5], traits.getTrait(PrimeTraits.CHR));

    // Net traits for female Half-Elves = STR-1, CON+1, CHR+1
    MsgCtrl.msgln("\t Gender = " + _gender);
    traits = _gender.adjustTraitsForGender(traits);
    MsgCtrl.msgln("\t STR-1, CON+1, CHR+1 net female adj: " + traits.toString());
    assertEquals(original[0] - 1, traits.getTrait(PrimeTraits.STR));
    assertEquals(original[1], traits.getTrait(PrimeTraits.INT));
    assertEquals(original[2], traits.getTrait(PrimeTraits.WIS));
    assertEquals(original[3] + 1, traits.getTrait(PrimeTraits.CON));
    assertEquals(original[4], traits.getTrait(PrimeTraits.DEX));
    assertEquals(original[5] + 1, traits.getTrait(PrimeTraits.CHR));
  }


  /**
   * @Not.Needed int calcHeight(int min, int avg) -- test given in base class
   */
  @Test
  public void testCalcHeight()
  {
    MsgCtrl.auditMsgsOn(false);
    MsgCtrl.errorMsgsOn(false);
    MsgCtrl.where(this);

    MsgCtrl.msgln(MsgCtrl.NOTEST + MsgCtrl.WRAPPER);
  }


  /**
   * @Not.Needed int calcHeight(int min, int avg) -- test given in base class
   */
  @Test
  public void testCalcWeight()
  {
    MsgCtrl.auditMsgsOn(false);
    MsgCtrl.errorMsgsOn(false);
    MsgCtrl.where(this);

    MsgCtrl.msgln(MsgCtrl.NOTEST + MsgCtrl.WRAPPER);
  }


  /**
   * @Normal.Test String getRaceLang() -- 50% chance to know Elvish
   */
  @Test
  public void testGetRaceLang()
  {
    MsgCtrl.auditMsgsOn(false);
    MsgCtrl.errorMsgsOn(false);
    MsgCtrl.where(this);

    int[] vals = new int[NBR_LOOPS];

    // Generate many Half-Elves and see how many times they know elvish
    HalfElf helf = new HalfElf(new Gender("male"), "black");
    assertNotNull(helf);
    for (int k = 0; k < NBR_LOOPS; k++) {
      String lang = helf.getRaceLang();
      vals[k] = (lang.isEmpty()) ? -1 : 1;
    }
    double avg = Utilities.average(vals);
    MsgCtrl.msg("\n\t Lang count after " + NBR_LOOPS + " tries = " + avg);
    // About half of the Half-Elves should know elvish
    assertEquals(0.0, avg, Chronos.TOLERANCE);
  }

  

} // end of TestHalfElf.java class
