/**
 * TestQAFileScan.java Copyright (c) 2016, Carolla Development, Inc. All Rights Reserved
 * 
 * Permission to make digital or hard copies of all or parts of this work for commercial use is
 * prohibited. To republish, to post on servers, to reuse, or to redistribute to lists, requires
 * prior specific permission and/or a fee. Request permission to use from Carolla Development, Inc.
 * by email: acline@carolla.com
 */


package test.pdc;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import mylib.MsgCtrl;
import pdc.QAFileScan;

/**
 * @author --generated by QA Tool--
 * @version July 26, 2016 // original <br>
 *          July 26, 2016 // autogen: QA Tool added missing test methods <br>
 *          August 1, 2016 // autogen: QA Tool added missing test methods <br>
 *          Nov 24, 2016 // tested flag args <br>
 *          Dec 11, 2016 // furthet testing of commandLine flags <br>
 */
public class TestQAFileScan
{
   // Use this file, which has passed it tests, to check the audit flags
   private final String _targetFilepath =
         "/Projects/eChronos/QATool/QA_Tool/src/pdc/Prototype.java";


   /**
    * @throws java.lang.Exception
    */
   @BeforeClass
   public static void setUpBeforeClass() throws Exception
   {}

   /**
    * @throws java.lang.Exception
    */
   @AfterClass
   public static void tearDownAfterClass() throws Exception
   {}

   /**
    * @throws java.lang.Exception
    */
   @Before
   public void setUp() throws Exception
   {}

   /**
    * @throws java.lang.Exception
    */
   @After
   public void tearDown() throws Exception
   {
      MsgCtrl.auditMsgsOn(false);
      MsgCtrl.errorMsgsOn(false);
   }

   // ========================================================================
   // BEGIN TESTING
   // ========================================================================

   /**
    * @ERROR_TEST boolean verifyArgs(String[]) Too many args
    */
   @Test
   public void testVerifyArgs_BadArgCount()
   {
      MsgCtrl.auditMsgsOn(true);
      MsgCtrl.errorMsgsOn(true);
      MsgCtrl.where(this);

      String[] cmdArgs = {"-verbose", "-fileEcho", "-stubFail"};
      String[] cmdLine = new String[5];
      cmdLine[0] = _targetFilepath;
      cmdLine[1] = cmdArgs[0];
      cmdLine[2] = cmdArgs[1];
      cmdLine[3] = cmdArgs[2];
      cmdLine[4] = "Stuffing";
      // Run test too many args
      String errorMsg = QAFileScan.verifyArgs(cmdLine);
      assertTrue(errorMsg.equals(QAFileScan.ERRMSG_ARGNUMBER));
   }

   
   /**
    * @ERROR_TEST boolean verifyArgs(String[]) Null command line
    * @ERROR_TEST boolean verifyArgs(String[]) Empty command line
    * @ERROR_TEST boolean verifyArgs(String[]) Invalid filename
    * @ERROR_TEST boolean verifyArgs(String[]) File doesn't exist
    */
   @Test
   public void testVerifyArgsFileErrors()
   {
      MsgCtrl.auditMsgsOn(true);
      MsgCtrl.errorMsgsOn(true);
      MsgCtrl.where(this);

      // Run test with no command line
      String errorMsg = QAFileScan.verifyArgs(null);
      assertTrue(errorMsg.equals(QAFileScan.ERRMSG_NOCMDLINE));

      // Run test with no command line
      String[] args = {};
      errorMsg = QAFileScan.verifyArgs(args);
      assertTrue(errorMsg.equals(QAFileScan.ERRMSG_NOCMDLINE));

      // Run test with non-java file name
      String[] cmdLine = new String[1];
      cmdLine[0] = "/Projects/eChronos/QATool/QA_Tool/src/pdc/Prototype";
      errorMsg = QAFileScan.verifyArgs(cmdLine);
      assertTrue(errorMsg.equals(QAFileScan.ERRMSG_BADFILE));

      // Run test with java file name that cannot be found
      cmdLine = new String[1];
      cmdLine[0] = "/Projects/eChronos/QATool/QA_Tool/src/pdc/Protype.java";
      errorMsg = QAFileScan.verifyArgs(cmdLine);
      assertTrue(errorMsg.equals(QAFileScan.ERRMSG_FILE_NOTFOUND));
   }


   /**
    * @NORMAL_TEST boolean verifyArgs(String[]) Verify that no flags will set all flags to false
    */
   @Test
   public void testVerifyArgs()
   {
      MsgCtrl.auditMsgsOn(true);
      MsgCtrl.errorMsgsOn(true);
      MsgCtrl.where(this);

      String[] cmdArgs = {"-verbose", "-fileEcho", "-stubFail"};

      // Run test with no args in command line
      String[] cmdLine = new String[1];
      cmdLine[0] = _targetFilepath;
      QAFileScan.verifyArgs(cmdLine);
      assertFalse(QAFileScan._verbose);
      assertFalse(QAFileScan._fileEcho);
      assertFalse(QAFileScan._stubFail);

      // Run test with -verbose flag
      cmdLine = new String[2];
      cmdLine[0] = _targetFilepath;
      cmdLine[1] = cmdArgs[0];
      QAFileScan.verifyArgs(cmdLine);
      assertTrue(QAFileScan._verbose);
      assertFalse(QAFileScan._fileEcho);
      assertFalse(QAFileScan._stubFail);
      clearFlags();

      // Run test with -fileEcho flag
      cmdLine = new String[2];
      cmdLine[0] = _targetFilepath;
      cmdLine[1] = cmdArgs[1];
      QAFileScan.verifyArgs(cmdLine);
      assertFalse(QAFileScan._verbose);
      assertTrue(QAFileScan._fileEcho);
      assertFalse(QAFileScan._stubFail);
      clearFlags();

      // Run test with -stubFail flag
      cmdLine = new String[2];
      cmdLine[0] = _targetFilepath;
      cmdLine[1] = cmdArgs[2];
      QAFileScan.verifyArgs(cmdLine);
      assertFalse(QAFileScan._verbose);
      assertFalse(QAFileScan._fileEcho);
      assertTrue(QAFileScan._stubFail);
      clearFlags();

      // Run test with -verbose and -fileEcho flag in reverse order
      cmdLine = new String[3];
      cmdLine[0] = _targetFilepath;
      cmdLine[1] = cmdArgs[1];
      cmdLine[2] = cmdArgs[0];
      QAFileScan.verifyArgs(cmdLine);
      assertTrue(QAFileScan._verbose);
      assertTrue(QAFileScan._fileEcho);
      assertFalse(QAFileScan._stubFail);
      clearFlags();

      // Run test with all flags set in non-alphabetical order
      cmdLine = new String[4];
      cmdLine[0] = _targetFilepath;
      cmdLine[1] = cmdArgs[1];
      cmdLine[2] = cmdArgs[2];
      cmdLine[3] = cmdArgs[0];
      QAFileScan.verifyArgs(cmdLine);
      assertTrue(QAFileScan._verbose);
      assertTrue(QAFileScan._fileEcho);
      assertTrue(QAFileScan._stubFail);
      clearFlags();
   }


   // ========================================================================
   // Private Helper Methods
   // ========================================================================

   // Clear the flags set during testing
   private void clearFlags()
   {
      QAFileScan._verbose = false;
      QAFileScan._fileEcho = false;
      QAFileScan._stubFail = false;
   }


} 	// end of TestQAFileScan.java class
