/**
 * TestSrcReader.java Copyright (c) 2016, Alan Cline. All Rights Reserved.
 * 
 * Permission to make digital or hard copies of all or parts of this work for commercial use is
 * prohibited. To republish, to post on servers, to reuse, or to redistribute to lists, requires
 * prior specific permission and/or a fee. Request permission to use from acline@carolla.com.
 */

package test.pdc;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import java.io.File;
import java.util.ArrayList;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import mylib.MsgCtrl;
import pdc.SrcReader;

/**
 * @author --generated by QA Tool--
 * @version December 21, 2016 // original <br>
 *          December 21, 2016 // autogen: QA Tool added missing test methods <br>
 */
public class TestSrcReader
{
   private SrcReader _srcRdr = null;

   // Name of source file to scan for testing
   static private final String TARGET_PATHNAME =
         "/Projects/eChronos/QATool/QA_Tool/src/pdc/TargetSrcFile.java";

   /**
    * @throws java.lang.Exception
    */
   @BeforeClass
   public static void setUpBeforeClass() throws Exception
   {}

   /**
    * @throws java.lang.Exception
    */
   @AfterClass
   public static void tearDownAfterClass() throws Exception
   {}

   /**
    * @throws java.lang.Exception
    */
   @Before
   public void setUp() throws Exception
   {
      _srcRdr = new SrcReader();
      assertNotNull(_srcRdr);
   }

   /**
    * @throws java.lang.Exception
    */
   @After
   public void tearDown() throws Exception
   {
      MsgCtrl.auditMsgsOn(false);
      MsgCtrl.errorMsgsOn(false);
      _srcRdr = null;
   }


   // ===============================================================================
   // BEGIN TESTING
   // ===============================================================================

   /**
    * @NORMAL_TEST void fileScan(File)
    */
   @Test
   public void testFileScan_MissingFile()
   {
      MsgCtrl.auditMsgsOn(true);
      MsgCtrl.errorMsgsOn(true);
      MsgCtrl.where(this);

      // Null file input
      ArrayList<String> srcList = _srcRdr.fileScan(null);
      assertNull(srcList);

      // Deliberately invalid file
      File badFile = new File("/Projects/eChronos/QATool/QA_Tool/src/pdc/dummy.java");
      srcList = _srcRdr.fileScan(badFile);
      assertNull(srcList);

      // A test file instead of a source file
      File testFile =
            new File("/Projects/eChronos/QATool/QA_Tool/src/test/pdc/TestTargetSrcFile.java");
      try {
         srcList = _srcRdr.fileScan(testFile);
         assertEquals(0, srcList.size());
      } catch (IllegalArgumentException ex) {
         MsgCtrl.msgln("\tExpected Exception thrown");
      }
   }


   /**
    * @NORMAL_TEST void fileScan(File)
    */
   @Test
   public void testFileScan()
   {
      MsgCtrl.auditMsgsOn(true);
      MsgCtrl.errorMsgsOn(true);
      MsgCtrl.where(this);

      ArrayList<String> srcList = _srcRdr.fileScan(new File(TARGET_PATHNAME));
      assertEquals(2, srcList.size());
   }


   /**
    * @NORMAL_TEST void scan(File)
    */
   @Test
   public void testScan()
   {
      MsgCtrl.auditMsgsOn(true);
      MsgCtrl.errorMsgsOn(true);
      MsgCtrl.where(this);

      MsgCtrl.errMsgln("\t\t TEST METHOD NOT YET IMPLEMENTED");
   }


   /**
    * @NORMAL_TEST void scanResults()
    */
   @Test
   public void testScanResults()
   {
      MsgCtrl.auditMsgsOn(true);
      MsgCtrl.errorMsgsOn(true);
      MsgCtrl.where(this);

      MsgCtrl.errMsgln("\t\t TEST METHOD NOT YET IMPLEMENTED");
   }


} 	// end of TestSrcReader.java class
