/**
 * TestQAFileScan.java Copyright (c) 2016, Carolla Development, Inc. All Rights Reserved
 * 
 * Permission to make digital or hard copies of all or parts of this work for commercial use is
 * prohibited. To republish, to post on servers, to reuse, or to redistribute to lists, requires
 * prior specific permission and/or a fee. Request permission to use from Carolla Development, Inc.
 * by email: acline@carolla.com
 */


package test.pdc;

import static org.junit.Assert.*;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import mylib.MsgCtrl;
import pdc.QAFileScan;

/**
 * @author --generated by QA Tool--
 * @version July 26, 2016 // original <br>
 *          July 26, 2016 // autogen: QA Tool added missing test methods <br>
 *          August 1, 2016 // autogen: QA Tool added missing test methods <br>
 *          Nov 24, 2016 // tested flag args <br>
 */
public class TestQAFileScan
{

   // Use this file, which has passed it tests, to check the audit flags
   private final String _targetFilepath =
         "/Projects/eChronos/QATool/QA_Tool/src/pdc/Prototype.java";


   /**
    * @throws java.lang.Exception
    */
   @BeforeClass
   public static void setUpBeforeClass() throws Exception
   {}

   /**
    * @throws java.lang.Exception
    */
   @AfterClass
   public static void tearDownAfterClass() throws Exception
   {}

   /**
    * @throws java.lang.Exception
    */
   @Before
   public void setUp() throws Exception
   {}

   /**
    * @throws java.lang.Exception
    */
   @After
   public void tearDown() throws Exception
   {
      MsgCtrl.auditMsgsOn(false);
      MsgCtrl.errorMsgsOn(false);
   }

   // ========================================================================
   // BEGIN TESTING
   // ========================================================================


   /**
    * @NORMAL_TEST boolean verifyArgs(String[]) Verify that no flags will set all flags to false
    */
   @Test
   public void testVerifyArgs()
   {
      MsgCtrl.auditMsgsOn(true);
      MsgCtrl.errorMsgsOn(true);
      MsgCtrl.where(this);

      String[] cmdArgs = new String[1];
      cmdArgs[0] = _targetFilepath;

      QAFileScan.verifyArgs(cmdArgs);
      assertFalse(QAFileScan._verbose);
      assertFalse(QAFileScan._fileEcho);
      assertFalse(QAFileScan._stubFail);
   }


} 	// end of TestQAFileScan.java class
