/** 
 * TestPrototype.java Copyright (c) 2016, Carolla Development, Inc. All Rights Reserved 
 * 
 * Permission to make digital or hard copies of all or parts of this work for 
 * commercial use is prohibited. To republish, to post on servers, to reuse, 
 * or to redistribute to lists, requires prior specific permission and/or a fee. 
 * Request permission to use from Carolla Development, Inc. by email: 
 * acline@carolla.com 
 */


package test.pdc;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import mylib.MsgCtrl;

/** 
 * @author --generated by QA Tool--
 * @version November 16, 2016    // original <br>
 *          November 16, 2016    // autogen: QA Tool added missing test methods <br>
 */
public class TestPrototype
{
	/** 
	 * @throws java.lang.Exception
 	 */ 
	@BeforeClass
	public static void setUpBeforeClass() throws Exception
	{ }

	/** 
	 * @throws java.lang.Exception
 	 */ 
	@AfterClass
	public static void tearDownAfterClass() throws Exception
	{ }

	/** 
	 * @throws java.lang.Exception
 	 */ 
	@Before
	public void setUp() throws Exception
	{ }

	/** 
	 * @throws java.lang.Exception
 	 */ 
	@After
	public void tearDown() throws Exception
	{ 
		MsgCtrl.auditMsgsOn(false);
		MsgCtrl.errorMsgsOn(false);
	}

	/**
 	 * @NORMAL_TEST File augmentTestFile(File, ArrayList, ArrayList)
	 */
	@Test
	public void testAugmentTestFile()
	{
		MsgCtrl.auditMsgsOn(true);
		MsgCtrl.errorMsgsOn(true);
		MsgCtrl.where(this);

      MsgCtrl.errMsgln("\t\t This test method is changed to see if any changes are made to it; ");
      MsgCtrl.errMsgln("\t\t or if duplicate methods are added.");
	}

	/**
 	 * @NORMAL_TEST ArrayList forceUnique(ArrayList)
	 */
	@Test
	public void testForceUnique()
	{
		MsgCtrl.auditMsgsOn(true);
		MsgCtrl.errorMsgsOn(true);
		MsgCtrl.where(this);

		MsgCtrl.errMsgln("\t\t TEST METHOD NOT YET IMPLEMENTED");
	}

	/**
 	 * @NORMAL_TEST File writeNewTestFile(File, ArrayList, ArrayList)
	 */
	@Test
	public void testWriteNewTestFile()
	{
		MsgCtrl.auditMsgsOn(true);
		MsgCtrl.errorMsgsOn(true);
		MsgCtrl.where(this);

		MsgCtrl.errMsgln("\t\t TEST METHOD NOT YET IMPLEMENTED");
	}

} 	// end of TestPrototype.java class
