/** 
 * TestTestWriter.java Copyright (c) 2016, Carolla Development, Inc. All Rights Reserved 
 * 
 * Permission to make digital or hard copies of all or parts of this work for 
 * commercial use is prohibited. To republish, to post on servers, to reuse, 
 * or to redistribute to lists, requires prior specific permission and/or a fee. 
 * Request permission to use from Carolla Development, Inc. by email: 
 * acline@carolla.com 
 */


package test.pdc;

import static org.junit.Assert.*; 
import org.junit.After; 
import org.junit.AfterClass; 
import org.junit.Before; 
import org.junit.BeforeClass; 
import org.junit.Test; 

import mylib.MsgCtrl;

/** 
 * @author --generated by QA Tool--
 * @version July 21, 2016 	// original <br>
 *          July 26, 2016 	// autogen: QA Tool added missing test methods <br>
 */
public class TestTestWriter
{
	/** 
	 * @throws java.lang.Exception
 	 */ 
	@BeforeClass
	public static void setUpBeforeClass() throws Exception
	{ }

	/** 
	 * @throws java.lang.Exception
 	 */ 
	@AfterClass
	public static void tearDownAfterClass() throws Exception
	{ }

	/** 
	 * @throws java.lang.Exception
 	 */ 
	@Before
	public void setUp() throws Exception
	{ }

	/** 
	 * @throws java.lang.Exception
 	 */ 
	@After
	public void tearDown() throws Exception
	{ 
		MsgCtrl.auditMsgsOn(false);
		MsgCtrl.errorMsgsOn(false);
	}

	/**
 	 * @NORMAL_TEST ArrayList convertToTestNames(ArrayList)
	 */
	@Test
	public void testConvertToTestNames()
	{
		MsgCtrl.auditMsgsOn(false);
		MsgCtrl.errorMsgsOn(false);
		MsgCtrl.where(this);

		fail("\t\tNot yet implemented");
	}

	/**
 	 * @NORMAL_TEST ArrayList getNewMethods(ArrayList, ArrayList)
	 */
	@Test
	public void testGetNewMethods()
	{
		MsgCtrl.auditMsgsOn(false);
		MsgCtrl.errorMsgsOn(false);
		MsgCtrl.where(this);

		fail("\t\tNot yet implemented");
	}

	/**
 	 * @NORMAL_TEST File getTargetTestFile(String)
	 */
	@Test
	public void testGetTargetTestFile()
	{
		MsgCtrl.auditMsgsOn(false);
		MsgCtrl.errorMsgsOn(false);
		MsgCtrl.where(this);

		fail("\t\tNot yet implemented");
	}

	/**
 	 * @NORMAL_TEST String makeTestFilename(String)
	 */
	@Test
	public void testMakeTestFilename()
	{
		MsgCtrl.auditMsgsOn(false);
		MsgCtrl.errorMsgsOn(false);
		MsgCtrl.where(this);

		fail("\t\tNot yet implemented");
	}

	/**
 	 * @NORMAL_TEST String makeTestName(String)
	 */
	@Test
	public void testMakeTestName()
	{
		MsgCtrl.auditMsgsOn(false);
		MsgCtrl.errorMsgsOn(false);
		MsgCtrl.where(this);

		fail("\t\tNot yet implemented");
	}

	/**
 	 * @NORMAL_TEST File makeTestPath(File)
	 */
	@Test
	public void testMakeTestPath()
	{
		MsgCtrl.auditMsgsOn(false);
		MsgCtrl.errorMsgsOn(false);
		MsgCtrl.where(this);

		fail("\t\tNot yet implemented");
	}

	/**
 	 * @NORMAL_TEST void writeResults()
	 */
	@Test
	public void testWriteResults()
	{
		MsgCtrl.auditMsgsOn(false);
		MsgCtrl.errorMsgsOn(false);
		MsgCtrl.where(this);

		fail("\t\tNot yet implemented");
	}

	/**
 	 * @NORMAL_TEST File writeTestFile(File, ArrayList)
	 */
	@Test
	public void testWriteTestFile()
	{
		MsgCtrl.auditMsgsOn(false);
		MsgCtrl.errorMsgsOn(false);
		MsgCtrl.where(this);

		fail("\t\tNot yet implemented");
	}

} 	// end of TestTestWriter.java class
