/** 
 * TestTestWriter.java Copyright (c) 2017, Alan Cline. All Rights Reserved. 
 * 
 * Permission to make digital or hard copies of all or parts of this work for 
 * commercial use is prohibited. To republish, to post on servers, to reuse, 
 * or to redistribute to lists, requires prior specific permission and/or a fee. 
 * Request permission to use from acline@carolla.com. 
 */

package test.pdc;

import static org.junit.Assert.*; 
import org.junit.After; 
import org.junit.AfterClass; 
import org.junit.Before; 
import org.junit.BeforeClass; 
import org.junit.Test; 

import mylib.MsgCtrl;

/** 
 * @author --generated by QA Tool--
 * @version April 25, 2017    // original <br>
 */
public class TestTestWriter
{
	/** 
	 * @throws java.lang.Exception
 	 */ 
	@BeforeClass
	public static void setUpBeforeClass() throws Exception
	{ }

	/** 
	 * @throws java.lang.Exception
 	 */ 
	@AfterClass
	public static void tearDownAfterClass() throws Exception
	{ }

	/** 
	 * @throws java.lang.Exception
 	 */ 
	@Before
	public void setUp() throws Exception
	{ }

	/** 
	 * @throws java.lang.Exception
 	 */ 
	@After
	public void tearDown() throws Exception
	{ 
		MsgCtrl.auditMsgsOn(false);
		MsgCtrl.errorMsgsOn(false);
	}


// ===============================================================================
//		 BEGIN TESTING
// ===============================================================================

	/**
 	 * @Normal.Test File augmentTestFile(File, Map)
	 */
	@Test
	public void testAugmentTestFile()
	{
		MsgCtrl.auditMsgsOn(true);
		MsgCtrl.errorMsgsOn(true);
		MsgCtrl.where(this);

		fail("TEST METHOD NOT YET IMPLEMENTED");
	}


	/**
 	 * @Normal.Test File writeNewTestFile(File, Map)
	 */
	@Test
	public void testWriteNewTestFile()
	{
		MsgCtrl.auditMsgsOn(true);
		MsgCtrl.errorMsgsOn(true);
		MsgCtrl.where(this);

		fail("TEST METHOD NOT YET IMPLEMENTED");
	}


	/**
 	 * @Normal.Test String makeTestFilename(String)
	 */
	@Test
	public void testMakeTestFilename()
	{
		MsgCtrl.auditMsgsOn(true);
		MsgCtrl.errorMsgsOn(true);
		MsgCtrl.where(this);

		fail("TEST METHOD NOT YET IMPLEMENTED");
	}


	/**
 	 * @Normal.Test void writeResults()
	 */
	@Test
	public void testWriteResults()
	{
		MsgCtrl.auditMsgsOn(true);
		MsgCtrl.errorMsgsOn(true);
		MsgCtrl.where(this);

		fail("TEST METHOD NOT YET IMPLEMENTED");
	}


} 	// end of TestTestWriter.java class
