/**
 * TestNPCRegistry.java Copyright (c) 2017, Alan Cline. All Rights Reserved.
 * 
 * Permission to make digital or hard copies of all or parts of this work for commercial use is
 * prohibited. To republish, to post on servers, to reuse, or to redistribute to lists, requires
 * prior specific permission and/or a fee. Request permission to use from acline@carolla.com.
 */

package chronos.test.pdc.registry;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.fail;

import java.util.ArrayList;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import chronos.pdc.NPC;
import chronos.pdc.registry.NPCRegistry;
import mylib.MsgCtrl;

/**
 * @author --generated by QA Tool--
 * @version July 31, 2017 // original <br>
 */
public class TestNPCRegistry
{
  static private NPCRegistry _npcReg;

  /**
   * @throws java.lang.Exception -- general catch-all for exceptions not caught by the tests
   */
  @BeforeClass
  public static void setUpBeforeClass() throws Exception
  {
    _npcReg = new NPCRegistry();
    assertNotNull(_npcReg);
  }

  /**
   * @throws java.lang.Exception -- general catch-all for exceptions not caught by the tests
   */
  @AfterClass
  public static void tearDownAfterClass() throws Exception
  {
    _npcReg = null;
  }

  /**
   * @throws java.lang.Exception -- general catch-all for exceptions not caught by the tests
   */
  @Before
  public void setUp() throws Exception
  {}

  /**
   * @throws java.lang.Exception -- general catch-all for exceptions not caught by the tests
   */
  @After
  public void tearDown() throws Exception
  {
    MsgCtrl.auditMsgsOn(false);
    MsgCtrl.errorMsgsOn(false);
  }


  // ===============================================================================
  // BEGIN TESTING
  // ===============================================================================

  /**
   * @Normal.Test NPCRegistry() -- confirm data is ok
   */
  @Test
  public void testCtor()
  {
    MsgCtrl.auditMsgsOn(true);
    MsgCtrl.errorMsgsOn(true);
    MsgCtrl.where(this);

    // Verify: there are 31 NPCs in the registry
    int expEntries = 16;
    ArrayList<NPC> entryList = (ArrayList<NPC>) _npcReg.getAll();
    assertNotNull(entryList);
    int len = entryList.size();
    MsgCtrl.msgln("\t There are " + len + " NPCs in the registry");
    assertEquals(expEntries, len);

    // Check the first and last of the occupations
    String name1 = entryList.get(0).getName();
    String name2 = entryList.get(expEntries - 1).getName();
    MsgCtrl.msgln("\t The first NPC is " + name1);
    MsgCtrl.msgln("\t The last NPC is " + name2);
    assertEquals("Sal", name1);
    assertEquals("The Sheriff", name2); 

    // Trying to get one more should lead to an error
    try {
      entryList.get(expEntries).getName();
      fail(MsgCtrl.EXCEPTION_NOT_THROWN);
    } catch (IndexOutOfBoundsException ibex) {
      MsgCtrl.msgln(MsgCtrl.EXP_EXCEPTION + ibex.getMessage());
    }
  }


  /**
   * @Not.Needed NPC getNPC(String) -- getter
   */
  @Test
  public void testGetNPC()
  {
    MsgCtrl.auditMsgsOn(true);
    MsgCtrl.errorMsgsOn(true);
    MsgCtrl.where(this);
    MsgCtrl.msgln(MsgCtrl.NOTEST  + MsgCtrl.GETTER);
  }


  /**
   * @Not.Needed void initialize() -- tested above
   */
  @Test
  public void testInitialize()
  {
    MsgCtrl.auditMsgsOn(true);
    MsgCtrl.errorMsgsOn(true);
    MsgCtrl.where(this);
    MsgCtrl.msgln(MsgCtrl.NOTEST  + MsgCtrl.PRIMITIVE);
  }


} // end of TestNPCRegistry.java class
