/**
 * TestOccupationRegistry.java Copyright (c) 2017, Alan Cline. All Rights Reserved.
 * 
 * Permission to make digital or hard copies of all or parts of this work for commercial use is
 * prohibited. To republish, to post on servers, to reuse, or to redistribute to lists, requires
 * prior specific permission and/or a fee. Request permission to use from acline@carolla.com.
 */

package chronos.test.pdc.registry;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.fail;

import java.util.ArrayList;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import chronos.pdc.Occupation;
import chronos.pdc.registry.OccupationRegistry;
import mylib.MsgCtrl;

/**
 * @author --generated by QA Tool--
 * @version July 30, 2017 // original <br>
 */
public class TestOccupationRegistry
{
  static private OccupationRegistry _ocpReg;


  /**
   * @throws java.lang.Exception -- general catch-all for exceptions not caught by the tests
   */
  @BeforeClass
  public static void setUpBeforeClass() throws Exception
  {
    _ocpReg = new OccupationRegistry();
    assertNotNull(_ocpReg);
  }

  /**
   * @throws java.lang.Exception -- general catch-all for exceptions not caught by the tests
   */
  @AfterClass
  public static void tearDownAfterClass() throws Exception
  {
    _ocpReg = null;
  }

  /**
   * @throws java.lang.Exception -- general catch-all for exceptions not caught by the tests
   */
  @Before
  public void setUp() throws Exception
  {}

  /**
   * @throws java.lang.Exception -- general catch-all for exceptions not caught by the tests
   */
  @After
  public void tearDown() throws Exception
  {
    MsgCtrl.auditMsgsOn(false);
    MsgCtrl.errorMsgsOn(false);
  }


  // ===============================================================================
  // BEGIN TESTING
  // ===============================================================================

  /**
   * @Normal.Test OccupationRegistry() -- confirm data is ok
   */
  @Test
  public void testCtor()
  {
    MsgCtrl.auditMsgsOn(false);
    MsgCtrl.errorMsgsOn(false);
    MsgCtrl.where(this);

    // Verify: there are 31 occupations in the occupation registry
    int nbrOcps = 31;
    ArrayList<Occupation> ocpList = (ArrayList<Occupation>) _ocpReg.getAll();
    assertNotNull(ocpList);
    int ocplen = ocpList.size();
    MsgCtrl.msgln("\t There are " + ocplen + " occupations in the registry");
    assertEquals(nbrOcps, ocplen);

    // Check the first and last of the occupations
    String ocp1Name = ocpList.get(0).getName();
    String ocp2Name = ocpList.get(nbrOcps-1).getName();
    MsgCtrl.msgln("\t The first occupation is " + ocp1Name);
    MsgCtrl.msgln("\t The last occupation is " + ocp2Name);
    assertEquals("Academic", ocp1Name);
    assertEquals("Drifter", ocp2Name); // usually placed last in the registry
    
    // Trying to get one more should lead to an error
    try {
        ocpList.get(nbrOcps).getName();
        fail(MsgCtrl.EXCEPTION_NOT_THROWN);
    } catch (IndexOutOfBoundsException ibex) {
      MsgCtrl.msgln(MsgCtrl.EXP_EXCEPTION + ibex.getMessage());
    }
  }


  /**
   * @Not.Needed void initialize() -- tested during ctor test
   */
  @Test
  public void testInitialize()
  {
    MsgCtrl.auditMsgsOn(false);
    MsgCtrl.errorMsgsOn(false);
    MsgCtrl.where(this);
    MsgCtrl.msgln(MsgCtrl.NOTEST  + MsgCtrl.PRIMITIVE);
  }


  /**
   * @Not.Needed Occupation getOccupation(String) -- getter
   */
  @Test
  public void testGetOccupation()
  {
    MsgCtrl.auditMsgsOn(false);
    MsgCtrl.errorMsgsOn(false);
    MsgCtrl.where(this);
    MsgCtrl.msgln(MsgCtrl.NOTEST  + MsgCtrl.GETTER);
  }


  /**
   * @Not.Needed List getOccupationList() -- used in other tests
   */
  @Test
  public void testGetOccupationList()
  {
    MsgCtrl.auditMsgsOn(false);
    MsgCtrl.errorMsgsOn(false);
    MsgCtrl.where(this);
    MsgCtrl.msgln(MsgCtrl.NOTEST  + MsgCtrl.PRIMITIVE);
  }


} // end of TestOccupationRegistry.java class
