/** 
 * UnitTestSuite.java Copyright (c) 2016, Carolla Development, Inc. All Rights Reserved 
 * 
 * Permission to make digital or hard copies of all or parts of this work for 
 * commercial use is prohibited. To republish, to post on servers, to reuse, 
 * or to redistribute to lists, requires prior specific permission and/or a fee. 
 * Request permission to use from Carolla Development, Inc. by email: 
 * acline@carolla.com 
 */

package test;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import test.pdc.TestFileMap;
import test.pdc.TestSuiteBuilder;
import test.pdc.TestTestTemplate;
import test.pdc.subDir.TestSubDirSource;

/**
 * Run all unit tests for the project.
 * 
 * @author --generated by QA Tool--
 * @version March 23, 2016 	// original <br>
 */

@RunWith(Suite.class)
@Suite.SuiteClasses( {

		/** Base Test Files */
		TestPrototype.class,
		TestQATool.class,

		/** PDC Test Files */
		TestSubDirSource.class,

		
		TestFileMap.class,
		TestPrototype.class,
		TestQATool.class,
		TestSuiteBuilder.class,
		TestTestTemplate.class,

		/** CIV Test Files */

		/** DMC Test Files */

}) 

 public class UnitTestSuite { } 
 // end of class
