#!/bin/bash

# In order to get this file to run when you push to GitHub
# you must create a symlink between the git_hooks folder and
# your .git/hooks directory. Suggested commands below.
#
# cd .git/hooks
# ln -s ../../git_hooks/pre-push pre-push
#
# You can verify that it works by making a minor change and
# then pushing it to the repo.

cd $(git rev-parse --show-toplevel)/Adventurer

echo running pre-push script

#Run script command here
# To get ant to return JUnit failures, add this property to the junit xml field
# in question <junit haltonfailure="yes"
#ant AdventurerTestSuite && ant IntegrationSuite

RESULT=$?
[ $RESULT -ne 0 ] && exit 1
exit 0
